---

- name: fetch latest terraform version
  uri:
    url: https://checkpoint-api.hashicorp.com/v1/check/terraform
  register: terraform_latest_version
  when: terraform_version == "latest"

- name: Check terraform version
  command: "terraform --version -json"
  failed_when: false
  changed_when: false
  register: terraform_old_version

- name: consolidate values
  set_fact:
    terraform_old_version: '{{ terraform_old_version.rc | ternary("", (terraform_old_version.stdout | default("0") | from_json).terraform_version) | default("") }}'
    terraform_version: '{{ (terraform_version != "latest") | ternary(terraform_version, (terraform_latest_version.content | default("0") | from_json).current_version) }}'

- name: Download and install terraform for {{ ansible_system }} on {{ ansible_architecture }}
  unarchive:
    url: https://releases.hashicorp.com//terraform_{{ terraform_version }}_{{ ansible_system|lower }}_{{ terraform_supported_architecture[ansible_architecture] }}.zip
    dest: "{{ terraform_dir }}"
  when: (ansible_architecture in terraform_supported_architectures) and (terraform_old_version != terraform_version)

...
