---
- name: Install packages
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - curl
    - jq
    - unzip

- name: extract latest version number
  block:

  - name: fetch latest terraform version
    shell: curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version'
    args:
      executable: /bin/bash
    register: latest_terraform_version

  - name: set terraform_version
    set_fact:
      terraform_version: "{{ latest_terraform_version.stdout }}"

  when: terraform_version == "latest"

- name: Check terraform version
  shell: "terraform --version 2>&1 | grep {{ terraform_version }}"
  failed_when: false
  changed_when: false
  register: terraform_versions_match

- include: download.yml
  when: terraform_versions_match.rc != 0

- name: Unarchive Terraform archive
  unarchive:
    src: /tmp/terraform-{{terraform_version}}.zip
    dest: "/usr/local/bin"
    copy: no
  when: terraform_versions_match.rc != 0
...
