---
- name: Check terraform version
  shell: "terraform --version 2>&1 | grep {{terraform_version}}"
  failed_when: false
  changed_when: false
  register: terraform_versions_match

- include: download.yml
  when: terraform_versions_match.rc != 0

- name: Install unzip to unarchive terraform
  apt:
    pkg: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - unzip

- name: Unarchive Terraform archive
  unarchive:
    src: /tmp/terraform-{{terraform_version}}.zip
    dest: "/usr/local/bin"
    copy: no
  when: terraform_versions_match.rc != 0
...
